collections:
  - name: preachers
    label: Preachers
    folder: src/content/preachers
    media_folder: "{{media_folder}}/preachers"
    slug: "{{fields.fullName}}"
    summary: "{{fullName}}"
    fields:
      - name: firstName
        label: First Name
        widget: string
      - name: lastName
        label: Last Name
        widget: string
      - name: fullName
        label: Full Name
        widget: compute
        value: "{{fields.firstName}} {{fields.lastName}}"
      - name: isGuest
        label: Guest Preacher
        widget: boolean
        default: true
      - name: sortPriority
        label: Sort Priority
        widget: number
        default: 0
      - name: image
        label: Upload a Picture
        widget: image
        required: false
      - name: body
        label: Bio
        widget: markdown
        required: false
