collections:
  - name: sermons
    label: Sermons
    label_singular: Sermon
    folder: src/content/sermons
    media_folder: "{{media_folder}}/sermons"
    slug: "{{fields.date}}-{{fields.title}}"
    view_groups:
      - field: series
        label: Series
    fields:
      - name: title
        label: Sermon Title
        widget: string
      - name: date
        label: Date Preached
        widget: datetime
        format: "YYYY-MM-DD"
        type: date
      - name: series
        label: Sermon Series
        widget: relation
        collection: series
        display_fields: [title]
        search_fields: [title]
      - name: scriptures
        label: Sermon Texts
        label_singular: Sermon Text
        required: false
        widget: list
        field: { name: reference, label: Scripture Reference, widget: string }
      - name: preacher
        label: Preacher
        widget: relation
        collection: preachers
        display_fields: [fullName]
        search_fields: [fullName]
      - name: mediaURL
        label: Media URL
        widget: string
        required: false
      - name: bulletinURL
        label: Bulletin URL
        widget: string
        required: false
      - name: body
        label: Notes
        widget: markdown
        required: false
