# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: tmykkanen/astro-church

media_folder: /src/assets
# public_folder: /media

collections:
  - name: config
    label: Configuration
    files:
      - name: site
        label: Site
        file: src/content/config/site.yaml
        media_folder: "{{media_folder}}/site"
        fields:
          - name: churchName
            label: Church Name
            widget: object
            fields:
              - name: name
                label: Name
                widget: string
              - name: showInHeader
                label: Show In Header
                widget: boolean
                default: true
          - name: churchDescription
            label: Church Description
            widget: text
          - name: churchLogo
            label: Church Logo
            widget: object
            required: false
            fields:
              - name: image
                label: Logo Image
                widget: image
              - name: showInHeader
                label: Show In Header
                widget: boolean
                default: true
          - name: socials
            label: Social Media
            widget: list
            required: false
            fields:
              - name: name
                label: Name
                widget: string
              - name: icon
                label: Icon
                widget: string
                hint: Use identifier from https://simpleicons.org/
              - name: link
                label: Link
                widget: string
                type: url
              - name: tooltip
                label: Tooltip
                widget: string
                required: false
              - name: showInFooter
                label: Show In Footer
                widget: boolean
                default: true
      - name: homepage
        label: Homepage
        file: src/content/config/homepage.yaml
        media_folder: "{{media_folder}}/site"
        fields:
          - name: hero
            label: Hero Settings
            widget: object
            required: false
            fields:
              - name: text
                label: Hero Text
                widget: code
                default_language: html
              - name: bgImage
                label: Background Image
                widget: image
                required: false
          - name: cta
            label: Call to Action Settings
            widget: object
            required: false
            fields:
              - name: text
                label: CTA Text
                widget: code
                default_language: html
              - name: link
                label: CTA Link
                widget: string
                type: url
                required: false
      - name: footer
        label: Footer
        file: src/content/config/footer.yaml
        media_folder: "{{media_folder}}/site"
        fields:
          - name: sections
            label: Sections
            widget: list
            required: false
            fields:
              - &heading
                name: heading
                label: Heading
                widget: string
              # TODO: Markdown or code?
              - &content
                name: content
                label: Content
                widget: markdown
          # TODO: Add form resend config
          - name: subscribe
            label: Subscribe Form
            widget: object
            required: false
            fields:
              - &isActive
                name: isActive
                label: Activate Form
                widget: boolean
                default: true
              - *heading
              - *content
          - name: giving
            label: Giving
            widget: object
            required: false
            fields:
              - <<: *isActive
                label: Activate Giving
              - *heading
              - *content
              - name: link
                label: Link
                widget: string
                type: url
      - name: team
        label: Team
        file: src/content/config/team.yaml
        fields:
          - name: pageTitle
            label: Page Title
            widget: string
          - name: pageDescription
            label: Page Description
            widget: markdown
          - name: sections
            label: Sections
            widget: list
            required: false
            fields:
              - name: name
                label: Name
                widget: string
              - name: description
                label: Description
                widget: markdown
                required: false
              - name: entries
                label: Entries
                widget: list
                field:
                  name: person
                  label: Person
                  widget: relation
                  collection: team
                  display_fields: [fullName]
                  search_fields: [fullName]
      - name: blog
        label: Blog
        file: src/content/config/blog.yaml
        fields:
          - name: tags
            label: Tags
            widget: list
            min: 1
            field:
              name: tag
              label: Tag
              widget: string
      - name: theme
        label: Theme
        file: src/content/config/theme.yaml
        media_folder: "{{media_folder}}/site"
        fields:
          - name: customCss
            label: Custom Css
            widget: code
            default_language: css
            required: false
