sections:
  - heading: Sundays at 10am
    content: <address>123 Main Street</br>Albert Lea, MN 56007</address>
  - heading: Contact Us
    content: |-
      notarealemail@astro.church</br>
      (123) 456-7899
subscribe:
  isActive: true
  heading: Weekly Bulletin
  content: Subscribe below to our weekly bulletin.
giving:
  isActive: true
  heading: Give to Astro Church
  content: Click below to set up a one time or recurring gift to Astro Church.
  link: https://get.tithe.ly/
