hero:
  text:
    code: <span class='opacity-40'>Free, open-source template</span><span class='text-primary'> for building great church websites</span><span class='opacity-40'> with Astro</span>
    lang: html
  bgImage: /src/assets/site/hero-bg.webp
cta:
  text:
    lang: html
    code: 10 am Sundays | Click here for livestream
  link: https://www.youtube.com/
