churchName:
  name: Astro Church
  showInHeader: true
churchDescription: Astro theme for churches.
churchLogo:
  image: /src/assets/site/logoipsum-379.svg
  showInHeader: true
socials:
  - name: Youtube
    icon: youtube
    link: https://www.youtube.com
    tooltip: ''
    showInFooter: true
