churchName:
  name: Astro Church
  showInHeader: true
churchDescription: Astro theme for churches.
churchLogo:
  image: /src/assets/site/logoipsum-379.svg
  showInHeader: true
socials:
  - name: Youtube
    icon: youtube
    link: https://www.youtube.com
    showInFooter: true
  - name: Facebook
    icon: facebook
    link: https://www.facebook.com/
    showInFooter: true
  - name: Spotify
    icon: spotify
    link: https://open.spotify.com/
    showInFooter: true
  - name: Message
    icon: whatsapp
    link: sms:+11231231234
    tooltip: Click to send text message
    showInFooter: true
